
name: Patch Mikrotik RouterOS
on:
  schedule:
    - cron: "30 9 * * *"   # At UTC 09:30 (Beijing 17:30) on every day
  workflow_dispatch:  

jobs:
  Patch_Stable:
    uses: ./.github/workflows/patch_v7.yml
    with:
      channel: stable
      release: true
    secrets: inherit

  Patch_LongTerm:
    uses: ./.github/workflows/patch_v7.yml
    with:
      channel: long-term
      release: true
    secrets: inherit

  Patch_Testing:
    uses: ./.github/workflows/patch_v7.yml
    with:
      channel: testing
      release: true
    secrets: inherit

  Patch_Stable_V6:
    uses: ./.github/workflows/patch_v6.yml
    with:
      channel: stable
      release: true
    secrets: inherit

  Patch_LongTerm_V6:
    uses: ./.github/workflows/patch_v6.yml
    with:
      channel: long-term
      release: true
    secrets: inherit
